Application_server

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,3 +1,13 @@
-#!/usr/bin/env bash
-# Gracefully reloads Gunicorn.
-pgrep aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
+#!/usr/bin/env  bash
+# Find the PID of the Gunicorn master process
+PID=$(pgrep -f "gunicorn.*web_dynamic.2-hbnb:app")
+
+if [ -z "$PID" ]; then
+  echo "Gunicorn master process not found."
+  exit 1
+fi
+
+# Send a HUP signal to the Gunicorn master process
+kill -HUP $PID
+
+echo "Reloading Gunicorn master process (PID: $PID)."
